version: "3.3"

services:
  primary_db:
    image: mariadb
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
  backend:
    depends_on:
      - primary_db
    build:
      context: ./backend-v2
      dockerfile: Dockerfile
    command: denon start
    volumes:
      - ./backend-v2:/home/app
    ports:
      - 8500:8500
    expose:
      - 8500
    environment:
      DB_NAME: test
      DB_USER: test
      DB_PASSWORD: test
      DB_ROOT_PASSWORD: admin
      DEV_DB_MODE: save # clean up the databse
  frontend:
    build:
      context: ./frontend-v2
      dockerfile: Dockerfile
    command: tail -f /dev/null
    ports:
      - 5000:5000
      - 35729:35729 # livereload port
    expose:
      - 35729 #livereload port
      - 5000
    volumes:
      - ./frontend-v2:/home/app